---
# Secret dla wra≈ºliwych danych
apiVersion: v1
kind: Secret
metadata:
  name: qrscanner-secrets
  namespace: qrscanner
type: Opaque
stringData:
  DB_USER: root
  DB_PASSWORD: "change-me-secure-password-min-16-chars"
  JWT_SECRET: "change-me-secure-jwt-secret-min-32-chars"
